### PR TITLE
Fix build with Qt >= 5.15

### PR DESCRIPTION
**Pull request by schnitzeltony**
Fixes:
| ../git/sources/editor/tree/treeitemdelegate.cpp:144:18: error: aggregate 'QPainterPath path' has incomplete type and cannot be defined

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

### CODE REVIEW

**Comment by davy7125** [comment]
Merged, thank you
